import PUFFS2BTC from './PUFFS2BTC'
import BTC2PUFFS from './BTC2PUFFS'

import LTC2BTC from './LTC2BTC'
import BTC2LTC from './BTC2LTC'

import PUFFS2LTC from './PUFFS2LTC'
import LTC2PUFFS from './LTC2PUFFS'

import EOS2BTC from './EOS2BTC'
import BTC2EOS from './BTC2EOS'

import PUFFSTOKEN2BTC from './PUFFSTOKEN2BTC'
import BTC2PUFFSTOKEN from './BTC2PUFFSTOKEN'
import USDT2PUFFSTOKEN from './USDT2PUFFSTOKEN'
import PUFFSTOKEN2USDT from './PUFFSTOKEN2USDT'


export {
  PUFFS2BTC,
  BTC2PUFFS,

  LTC2BTC,
  BTC2LTC,

  PUFFS2LTC,
  LTC2PUFFS,

  EOS2BTC,
  BTC2EOS,

  PUFFSTOKEN2BTC,
  BTC2PUFFSTOKEN,
  USDT2PUFFSTOKEN,
  PUFFSTOKEN2USDT,
}
